### ISSUE TITLE
Create new dataset

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/off-category-classification#10]
Improve upon the https://github.com/openfoodfacts/off-category-classification/blob/master/download.sh to also be able to download images and OCR data.

It would may be great to have it as a python library instead of a shell script to be modular and be able to load needed data + avoid reloading data if it's already there (like images). It could also be differential.

Maybe for images (which is network/space consuming) we want to be able to fetch the one for which we don't yet have textual description), if this we take the approach of a simple textual feature extraction from images (see #6 )

We should have:
- data collection for a 'products' dataset (title, ingredients, nutritional data, 
- 'pictures' dataset (see note above)
- 'ocr' collection
- 'categories with an agribalyse match' dataset

see also:
- #9

**Comment by alexgarel** [comment]
Note existing datasets: see https://github.com/openfoodfacts/robotoff-models/releases/tag/keras-category-classifier-xx-2.0

**Comment by teolemon** [comment]
http://static.openfoodfacts.org/images/products/ocr.jsonl.gz

**Comment by alexgarel** [comment]
I have created a harvesting script : https://github.com/openfoodfacts/off-category-classification/pull/25

It's running in production (it took 1h to do first 10%).

**Comment by alexgarel** [comment]
The script is already run.

We have:
- a small one with images https://openfoodfacts.org/data/dataforgood2022/small/predict_categories_dataset_documentation.txt
- a big one without images https://openfoodfacts.org/data/dataforgood2022/small/predict_categories_dataset_documentation.txt

**Comment by alexgarel** [comment]
I am reworking this to have:
- less information in the OCR: we decide with Anis that it could only keep raw text for OCR but indexed by image + add detected languages (at least those predicted >0.3). 
- add more fields as they may be used later. Add "ingredients" but remove ingredients_original_tags

**Comment by alexgarel** [comment]
I renamed the issue as we are not yet on an automated collection.

**Comment by alexgarel** [comment]
We have a new dataset, at same url: https://openfoodfacts.org/data/dataforgood2022/big/predict_categories_dataset_documentation.txt

In this new dataset, there are no entry without categories (as they are useless)

@tcayla , logo information is there with two files:
* 58M     logos_robotoff.jsonl.gz
* 16G     logos.tar
