### ISSUE TITLE
Use Nutrition as a complementary feature for off-category-classification

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/off-category-classification#11]
See how we can use features of nutrition, when we have them, to improve the model.

The focus here is on which pre-processing to use, how to mix with existing data, and trying to use them with title / ingredients to see if how it may improve the score.

Follow the line of having pre treatments in the tensorflow pipeline to ease model deployment.

**Comment by teolemon** [comment]
I believe this is fixed @raphael0202 ?
