### ISSUE TITLE
Training on Google Colab GPU crashes with "Check failed: work_element_count > 0 (0 vs. 0)"

### ISSUE THREAD

**Issue by streino** [openfoodfacts/off-category-classification#27]
Crash occurs during call to `model.fit`:
```
Starting training repeat 0
Starting training...
Temporary log directory: /tmp/tmpl8oocgla
Epoch 1/50
```

At this stage, Colab kernel dies with `Your session crashed for an unknown reason`.

Runtime logs (reverse chronological order):
|Timestamp|Level|Message|
|---|---|---|
|Apr 13, 2022, 12:16:55 PM|WARNING|WARNING:root:kernel 13b70611-6397-4150-b43d-5fe59485158c restarted|
|Apr 13, 2022, 12:16:55 PM|INFO|KernelRestarter: restarting kernel \(1/5), keep random ports|
|Apr 13, 2022, 12:16:54 PM|WARNING|2022-04-13 10:16:54\.701061: F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)|
|Apr 13, 2022, 12:16:02 PM|WARNING|2022-04-13 10:16:02\.533234: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.|
|Apr 13, 2022, 12:15:50 PM|INFO|Adapting to protocol v5\.1 for kernel 13b70611-6397-4150-b43d-5fe59485158c|
|Apr 13, 2022, 12:15:49 PM|INFO|Kernel started: 13b70611-6397-4150-b43d-5fe59485158c|
|Apr 13, 2022, 12:12:10 PM|INFO|Use Control-C to stop this server and shut down all kernels \(twice to skip confirmation).|
|Apr 13, 2022, 12:12:10 PM|INFO|http://172\.28.0.2:9000/|
|Apr 13, 2022, 12:12:10 PM|INFO|The Jupyter Notebook is running at:|

I used @8huit [Train.ipynb](https://colab.research.google.com/github/openfoodfacts/off-category-classification/blob/experiments/experiments/Train.ipynb) to reproduce. Running that notebook on Colab CPU VM works fine.

**Comment by 8huit** [comment]
Hey, that's great!

How long did it take to train on colab?
